# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - sunwebapis

on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  BOOKING_ROOT: './bookings'
  CUSTOMER_ROOT: './customers'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r ./bookings/requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            ${{ env.BOOKING_ROOT }}
            !venv/
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app-customer
          path: |
            ${{ env.CUSTOMER_ROOT }}
            !venv/

  deploy:
    defaults:
      run:
        working-directory: ${{ env.BOOKING_ROOT }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: ${{ env.BOOKING_ROOT }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'sunwebapis'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CFA37CE18E2C49D294BBDC684DE42A60 }}
          package:  ${{ env.BOOKING_ROOT }}

  deploy_customer:
    defaults:
      run:
        working-directory: ${{ env.CUSTOMER_ROOT }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-customer.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app-customer
          path: ${{ env.CUSTOMER_ROOT }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp-customer
        with:
          app-name: 'customerssunweb'
          slot-name: 'Production'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_CUSTOMER }}
          package:  ${{ env.CUSTOMER_ROOT }}